analyses_directory: analyses
plots_directory: plots
renders_directory: renders
tables_directory: tables
transformation_parameters: configuration/hyperparameters.npy

katago:
  executable: "C:/Go/KataGo/katago-v1.8.0-cuda11.2-windows-x64/katago.exe"
  configuration: "C:/Go/KataGo/katago-v1.8.0-cuda11.2-windows-x64/oracle.cfg"
  model: "C:/Go/KataGo/katago-v1.8.0-cuda11.2-windows-x64/kata1-b20c256x2-s5303129600-d1228401921.bin.gz"
  analysisThreads: 16
  searchThreads: 1
